### ISSUE TITLE
Fix emails not being sent

### ISSUE THREAD

**Issue by robertquitt** [CSUA/csua-backend#43]
Emails aren't being sent at all, including the error emails

**Comment by robertquitt** [comment]
I wasn't getting any emails from django, I looked into whether the django config was wrong

Figured out that mail wasn't being sent by doing the following:

```
robertq@tap:/webserver/CSUA-backend$ sudo -u www-data python3 manage.py shell
>>> from django.core.mail import send_mail
>>> send_mail('Hello', 'Hello, world', "django-errors@mail.csua.berkeley.edu", ['robertq@csua.berkeley.edu'])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.5/dist-packages/django/core/mail/backends/smtp.py", line 126, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.5/smtplib.py", line 862, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Must issue a STARTTLS command first', 'django-errors@mail.csua.berkeley.edu')
>>> from django.conf import settings
>>> settings.EMAIL_USE_TLS
False
>>> settings.EMAIL_USE_TLS = True
>>> send_mail('Hello', 'Hello, world', "django-errors@mail.csua.berkeley.edu", ['robertq@csua.berkeley.edu'])
1
```
